#!/usr/bin/env python3
"""Public façade for deterministic flashcard generation.

The implementation is split across ``mnemo.pipeline.flashcards`` modules, while
this module preserves the historical import surface and console entrypoint.
"""

from __future__ import annotations

from mnemo.pipeline.flashcards.authoring import (
    AiAuthoringError,
    CommandAiProvider,
    DeterministicAuthor,
    FileAiProvider,
    JsonAiAuthor,
    build_authoring_prompt,
)
from mnemo.pipeline.flashcards.cli import build_parser, main, parse_steps
from mnemo.pipeline.flashcards.io import analyze_retention, write_csv, write_json
from mnemo.pipeline.flashcards.models import (
    CARD_TYPES,
    CSV_FIELDS,
    DEFAULT_SEED,
    MAX_COMPONENTS,
    MAX_FRONT_WORDS,
    Card,
    GenerationConfig,
    SourceUnit,
    Violation,
)
from mnemo.pipeline.flashcards.parse import (
    assign_objectives,
    atomic_units,
    clone_unit,
    parse_content,
    plan_knowledge,
    starts_new_structured_line,
)
from mnemo.pipeline.flashcards.render import (
    answer_from_cloze,
    build_cards,
    build_extra,
    choose_card_type,
    declarative_statement,
    exact_answer_candidate,
    explanation_is_thin,
    first_alnum,
    group_by_topic,
    interleave_cards,
    is_generic_prompt,
    make_cloze,
    make_mnemonic,
    meaningful_cloze_candidate,
    normalize_image_alt,
    render_prompt,
    render_semantic_prompt,
    requires_context,
    reversible_definition,
    stable_card_id,
)
from mnemo.pipeline.flashcards.text import (
    definition_term,
    enumerated_components,
    has_cloze,
    parse_delimited_pair,
    parse_tags,
    protect_thousands_commas,
    semantic_tokens,
    slugify,
    split_independent_clauses,
    split_list_items,
    split_sentences,
    strip_html_and_cloze,
    word_count,
)
from mnemo.pipeline.flashcards.validate import (
    error,
    estimate_components,
    has_avoidable_topic_runs,
    image_alt_is_explanatory,
    looks_compound,
    step_uses_day,
    validate_card,
    validate_deck,
    warning,
)

__all__ = [
    "CARD_TYPES",
    "CSV_FIELDS",
    "DEFAULT_SEED",
    "MAX_COMPONENTS",
    "MAX_FRONT_WORDS",
    "Card",
    "GenerationConfig",
    "SourceUnit",
    "Violation",
    "AiAuthoringError",
    "CommandAiProvider",
    "DeterministicAuthor",
    "FileAiProvider",
    "JsonAiAuthor",
    "analyze_retention",
    "answer_from_cloze",
    "assign_objectives",
    "atomic_units",
    "build_authoring_prompt",
    "build_cards",
    "build_extra",
    "build_parser",
    "choose_card_type",
    "clone_unit",
    "declarative_statement",
    "definition_term",
    "enumerated_components",
    "error",
    "estimate_components",
    "exact_answer_candidate",
    "explanation_is_thin",
    "first_alnum",
    "group_by_topic",
    "has_avoidable_topic_runs",
    "has_cloze",
    "image_alt_is_explanatory",
    "interleave_cards",
    "is_generic_prompt",
    "looks_compound",
    "main",
    "make_cloze",
    "make_mnemonic",
    "meaningful_cloze_candidate",
    "normalize_image_alt",
    "parse_content",
    "parse_delimited_pair",
    "parse_steps",
    "parse_tags",
    "plan_knowledge",
    "protect_thousands_commas",
    "render_prompt",
    "render_semantic_prompt",
    "requires_context",
    "reversible_definition",
    "semantic_tokens",
    "slugify",
    "split_independent_clauses",
    "split_list_items",
    "split_sentences",
    "stable_card_id",
    "starts_new_structured_line",
    "step_uses_day",
    "strip_html_and_cloze",
    "validate_card",
    "validate_deck",
    "warning",
    "word_count",
    "write_csv",
    "write_json",
]


if __name__ == "__main__":
    raise SystemExit(main())
